### ISSUE TITLE
setfcomment appends random chars

### ISSUE THREAD

**Issue by 1-61803** [specious/osxutils#7]
It seems to happen randomly, see below. I noticed it especially with URLs.
```
$ touch foo
$ 
$ getfcomment foo 
$ 
$ setfcomment -c 'https://www.google.com' foo
Finder Comment set for foo
$ 
$ getfcomment foo 
https://www.google.comD
$ 
$ setfcomment -c 'https://www.google.com' foo
Finder Comment set for foo
$ 
$ getfcomment foo 
https://www.google.comD
$ 
$ setfcomment -c 'https://www.google.com' foo
Finder Comment set for foo
$ 
$ getfcomment foo 
https://www.google.com
```

**Comment by ryandesign** [comment]
The problem is in `MoreFESetComment` in setfcomment/setfcomment.c, where it converts the incoming Pascal string to a C string. A comment there says that `MoreFESetComment` was copied from Apple's MoreAppleEvents sample code. I cannot find that sample code on Apple's developer site anymore. I found a mirror of it on another site, but that copy of the code converts the Pascal string to a C string using `CopyPascalStringToC`. `CopyPascalStringToC` is deprecated however which is probably why osxutils isn't using it anymore.

It's unclear why setfcomment.c bothers converting the C string from `argv` into a Pascal string, only to convert it right back to a C string again. But rather than rework that, my PR just fixes the faulty Pascal to C string conversion.
